export default {
  "'coz": "because",
  "'d": " would",
  "'ll": " will",
  "'re": " are",
  "'em": " them",
  "'aight": "alright",
  abt: "about",
  acct: "account",
  altho: "although",
  asap: "as soon as possible",
  avg: "average",
  b4: "before",
  bc: "because",
  bday: "birthday",
  btw: "by the way",
  "'cause": "because",
  convo: "conversation",
  cya: "see ya",
  diff: "different",
  "doin'": "doing",
  dunno: "do not know",
  finna: "fixing to",
  "g'day": "good day",
  gimme: "give me",
  "goin'": "going",
  gonna: "going to",
  gotta: "got to",
  "havin'": "having",
  howdy: "how do you do",
  idk: "I do not know",
  ima: "I am going to",
  imma: "I am going to",
  innit: "is it not",
  iunno: "I do not know",
  kinda: "kind of",
  kk: "okay",
  lemme: "let me",
  "lovin'": "loving",
  luv: "love",
  msg: "message",
  "nothin'": "nothing",
  nvm: "nevermind",
  ofc: "of course",
  ppl: "people",
  prolly: "probably",
  pymnt: "payment",
  r: "are ",
  rlly: "really",
  rly: "really",
  rn: "right now",
  "somethin'": "something",
  spk: "spoke",
  sux: "sucks",
  tbh: "to be honest",
  thats: "that is",
  tho: "though",
  thx: "thanks",
  tlked: "talked",
  tmmw: "tomorrow",
  tmr: "tomorrow",
  tmrw: "tomorrow",
  u: "you",
  ur: "you are",
  wanna: "want to",
  whatcha: "What are you",
  whats: "what is",
  woulda: "would have",
};
